spring.application.name=demo

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/TUBES
spring.datasource.username=postgres
spring.datasource.password=sandi131005
# spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP Configuration
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000

server.port=8080

# Allow file uploads up to 10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Embedded Tomcat POST size (in bytes) - match 10MB
server.tomcat.max-swallow-size=10485760